import type { Patient, SurgeryType } from './types'

export const patients: Patient[] = [
  {
    id: '9921',
    name: 'Eleanor Miller',
    shortName: 'Eleanor M.',
    initials: 'EM',
    room: '402',
    age: 68,
    score: 42,
    previousScore: 54,
    trend: 'Declining',
    risk: 'High',
    dayOfRecovery: 4,
    surgeryType: 'Cardiac',
    recommendation: 'Flag for in-person assessment',
    observation:
      'Pause frequency increased, coherence dropped. Clinical check-in suggested. Observations recorded during the 08:00 AM screening show early signs of cognitive fluctuation. Speech patterns indicate higher effort for word retrieval compared to baseline.',
    signals: [
      { label: 'Response Latency', value: '+1.2s from baseline', type: 'latency',  direction: 'down' },
      { label: 'Speech Rate',      value: '120 wpm (−15%)',      type: 'speech',   direction: 'down' },
      { label: 'Recall Accuracy',  value: '74% (−10%)',          type: 'recall',   direction: 'down' },
      { label: 'Coherence',        value: 'Declining Trend',     type: 'coherence',direction: 'down' },
    ],
    chartData: [
      { day: 'Mon', score: 65 },
      { day: 'Tue', score: 62 },
      { day: 'Wed', score: 68 },
      { day: 'Thu', score: 72 },
      { day: 'Fri', score: 60 },
      { day: 'Sat', score: 50 },
      { day: 'Sun', score: 42 },
    ],
  },
  {
    id: '8842',
    name: 'Robert Jenkins',
    shortName: 'Robert J.',
    initials: 'RJ',
    room: '312',
    age: 71,
    score: 78,
    previousScore: 76,
    trend: 'Stable',
    risk: 'Med',
    dayOfRecovery: 6,
    surgeryType: 'Orthopedic',
    recommendation: 'Continue monitoring',
    observation:
      'Speech cadence and recall accuracy remain within expected post-operative norms. No significant deviations from yesterday\'s session.',
    signals: [
      { label: 'Response Latency', value: '+0.3s from baseline', type: 'latency',  direction: 'neutral' },
      { label: 'Speech Rate',      value: '138 wpm (−2%)',       type: 'speech',   direction: 'neutral' },
      { label: 'Recall Accuracy',  value: '84% (−1%)',           type: 'recall',   direction: 'neutral' },
      { label: 'Coherence',        value: 'Stable',              type: 'coherence',direction: 'up' },
    ],
    chartData: [
      { day: 'Mon', score: 72 },
      { day: 'Tue', score: 74 },
      { day: 'Wed', score: 73 },
      { day: 'Thu', score: 75 },
      { day: 'Fri', score: 76 },
      { day: 'Sat', score: 77 },
      { day: 'Sun', score: 78 },
    ],
  },
  {
    id: '7712',
    name: 'Alice Wong',
    shortName: 'Alice W.',
    initials: 'AW',
    room: '205',
    age: 55,
    score: 92,
    previousScore: 77,
    trend: 'Improving',
    risk: 'Med',
    dayOfRecovery: 3,
    surgeryType: 'Abdominal',
    recommendation: 'Continue current protocol',
    observation:
      'Significant improvement across all cognitive markers. Vocabulary richness and sentence completion rates have recovered to near-baseline levels.',
    signals: [
      { label: 'Response Latency', value: 'Within baseline',    type: 'latency',  direction: 'up' },
      { label: 'Speech Rate',      value: '152 wpm (+8%)',      type: 'speech',   direction: 'up' },
      { label: 'Recall Accuracy',  value: '91% (+12%)',         type: 'recall',   direction: 'up' },
      { label: 'Coherence',        value: 'Improving Trend',    type: 'coherence',direction: 'up' },
    ],
    chartData: [
      { day: 'Mon', score: 60 },
      { day: 'Tue', score: 65 },
      { day: 'Wed', score: 70 },
      { day: 'Thu', score: 75 },
      { day: 'Fri', score: 80 },
      { day: 'Sat', score: 87 },
      { day: 'Sun', score: 92 },
    ],
  },
  {
    id: '9955',
    name: 'Henry Baker',
    shortName: 'Henry B.',
    initials: 'HB',
    room: '410',
    age: 79,
    score: 65,
    previousScore: 65,
    trend: 'Stable',
    risk: 'Med',
    dayOfRecovery: 2,
    surgeryType: 'Vascular',
    recommendation: 'Continue monitoring',
    observation:
      'Early post-operative day. Scores are within expected range for Day 2. Baseline will need 2–3 more sessions to establish reliably.',
    signals: [
      { label: 'Response Latency', value: '+0.5s from baseline', type: 'latency',  direction: 'neutral' },
      { label: 'Speech Rate',      value: '131 wpm',             type: 'speech',   direction: 'neutral' },
      { label: 'Recall Accuracy',  value: '80%',                 type: 'recall',   direction: 'neutral' },
      { label: 'Coherence',        value: 'Establishing baseline', type: 'coherence', direction: 'neutral' },
    ],
    chartData: [
      { day: 'Mon', score: 0 },
      { day: 'Tue', score: 0 },
      { day: 'Wed', score: 0 },
      { day: 'Thu', score: 0 },
      { day: 'Fri', score: 0 },
      { day: 'Sat', score: 63 },
      { day: 'Sun', score: 65 },
    ],
  },
]

export const surgeryTypes: SurgeryType[] = [
  { value: 'orthopedic',  label: 'Orthopedic' },
  { value: 'cardiac',     label: 'Cardiac' },
  { value: 'abdominal',   label: 'Abdominal' },
  { value: 'vascular',    label: 'Vascular' },
  { value: 'neurological',label: 'Neurological' },
  { value: 'thoracic',    label: 'Thoracic' },
  { value: 'other',       label: 'Other' },
]
